# Generated by Django 4.2.3 on 2023-08-01 21:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoubleImageContent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_left', models.CharField(blank=True, max_length=255, null=True)),
                ('link_wrapper_left', models.URLField(blank=True, null=True)),
                ('image_left', models.ImageField(upload_to='content_images')),
                ('copy_left', models.TextField(blank=True, null=True)),
                ('name_right', models.CharField(blank=True, max_length=255, null=True)),
                ('link_wrapper_right', models.URLField(blank=True, null=True)),
                ('image_right', models.ImageField(upload_to='content_images')),
                ('copy_right', models.TextField(blank=True, max_length=510, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SingleImageContent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('link_wrapper', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='content_images')),
                ('copy', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_type', models.CharField(choices=[('single_image', 'Single Image'), ('double_image', 'Double Image'), ('products_list', 'Products List')], max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('double_image_content', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section', to='sections.doubleimagecontent')),
                ('single_image_content', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section', to='sections.singleimagecontent')),
            ],
            options={
                'ordering': ('sort_order',),
            },
        ),
        migrations.CreateModel(
            name='Button',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('content', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='button', to='sections.singleimagecontent')),
                ('content_left', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='button_left', to='sections.doubleimagecontent')),
                ('content_right', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='button_right', to='sections.doubleimagecontent')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
